# Generated by Django 4.1.5 on 2023-01-30 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oferta',
            name='ingredientes',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
