# Generated by Django 4.1.5 on 2023-01-30 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuApp', '0002_alter_oferta_ingredientes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oferta',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='items'),
        ),
    ]
